# Site settings
title: 127.0.0.1
description: >
  Personal home to Anfal's thoughts. You can find whatever he thinks about on daily basis and probably on what he is currently working on.

permalink: pretty

author:
  fullname: Anfal
  github: MAnfal
  linkedin: manfal
  email: null
  twitter: Muhammad_Anfal

gtag: UA-67493206-2

# Build settings
highlighter: null
markdown: kramdown

exclude: [
  'src',
  'webpack.mix.js',
  'tslint.json',
  'tsconfig.json',
  'package.json',
  'Gemfile',
  'Gemfile.lock',
  'definition-manifest.json',
  'node_modules',
  'tailwind.config.js',
  'package-lock.json',
  'mix-manifest.json',
  '.eslintrc',
  '.editorconfig',
  '.vscode',
  '.devcontainer'
]
