# Site settings
title: 127.0.0.1
description: >
  Personal home to Anfal's thoughts. You can find whatever he thinks about on daily basis and probably on what he is currently working on.

permalink: pretty

author:
  fullname: Anfal
  github: MAnfal
  linkedin: anfalmushtaq
  email: null
  twitter: AnfalMushtaq

gtag: UA-67493206-2

# Build settings
highlighter: null
markdown: kramdown
